crossityEnglishApp/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  omniauth_callbacks: "omniauth_callbacks"
  }
  root "top#index"
  get "/answers/:id", to: "answers#new"
  patch "/questions/:id", to: "questions#update"
  resources :users, only: [:show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only:[:create, :show, :new]
  resources :answers, only: [:new, :create, :edit, :update]
  resources :participants, only: [:create, :update, :show, :destroy]
  resources :asks, only: [:create, :update, :show]


end

crossityEnglishApp/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_one :feed_content, as: :content, dependent: :destroy

   #callback
  after_create :create_feed_content
  after_update :update_feed_content

  #validation
  validates_presence_of :user_id, :text

  def update_feed_content
    self.feed_content.update(updated_at: updated_at)
  end

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: question.group_id, updated_at: updated_at)
  end

end

crossityEnglishApp/app/models/ask.rb
class Ask < ActiveRecord::Base
  has_many :questions
  belongs_to :user
  validates_presence_of :text

end

crossityEnglishApp/app/models/feed_content.rb
class FeedContent < ActiveRecord::Base
  belongs_to :content, polymorphic: true
end

crossityEnglishApp/app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :questions, ->{ order("created_at DESC") }
  has_many :feed_contents, ->{ order("updated_at DESC") }
end

crossityEnglishApp/app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

crossityEnglishApp/app/models/question.rb
class Question < ActiveRecord::Base
  after_create :create_feed_content

  has_many :participants
  has_many :asks
  belongs_to :group
  belongs_to :user
  has_many :answers
  has_one :feed_content, as: :content, dependent: :destroy
  has_many :pushed_users, through: :participants, source: :user
  validates_presence_of :user_id, :group_id,:when, :where, :what


  def user_answer(user_id)
    def user_answer(user_id)
    Answer.find_by(user_id: user_id, question_id: id)
  end
  end

  def answered?(user)
    answers.exists?(user_id: user.id)
  end

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: group_id, updated_at: updated_at)
  end
end

crossityEnglishApp/app/models/social_profile.rb
class SocialProfile < ActiveRecord::Base
  belongs_to :user

  def set_values(omniauth)
    return if provider.to_s != omniauth['provider'].to_s || uid != omniauth['uid']
    credentials = omniauth['credentials']
    info = omniauth['info']

    self.access_token = credentials['refresh_token']
    self.access_secret = credentials['secret']
    self.credentials = credentials.to_json
    self.name = info['name']
    self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
end

crossityEnglishApp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,authentication_keys: [:email, :group_key]

  attr_accessor :group_key
  has_many :participants
  belongs_to :group
  has_many :questions, ->{order("created_at DESC")}, through: :participants
  has_many :answers, ->{ order("updated_at DESC") }
  has_many :answered_questions, through: :answers, source: :question
  has_many :social_profiles, dependent: :destroy

    #validation
  before_validation :group_key_to_id, if: :has_group_key?

  def social_profile(provider)
    social_profiles.select{ |sp| sp.provider == provider.to_s }.first
  end

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      group_key = conditions.delete(:group_key)
      group_id = Group.where(key: group_key).first
      email = conditions.delete(:email)

      # devise認証を、複数項目に対応させる
      if group_id && email
        where(conditions).where(["group_id = :group_id AND email = :email",
          { group_id: group_id, email: email }]).first
      elsif conditions.has_key?(:confirmation_token)
        where(conditions).first
      else
        false
      end
    end

    def has_group_key?
      group_key.present?
    end

    def group_key_to_id
      group = Group.where(key: group_key).first_or_create
      self.group_id = group.id
    end

    def name
    "#{family_name} #{first_name}"
    end

    def name_kana
    "#{family_name_kana} #{first_name_kana}"
    end

     has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
     validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
     def full_profile?
      avatar? && family_name? && first_name? && family_name_kana? && first_name_kana?
       end

end

crossityEnglishApp/app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :redirect, only: :new

  def new
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answer.question_id = @question.id
  end

  def create
    @answer = Answer.create(create_params)
  end

  def create_params
    params.require(:answer).permit(:question_id, :text).merge(user_id: current_user.id)
  end

  def redirect
    if Answer.exists?(question_id: params[:question_id], user_id: current_user.id)
      redirect_to :root
    end
  end

   def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
    @answer = Answer.find(params[:id])
    @question = @answer.question
    @answer.update(update_params)
  end

  def update_params
    params.require(:answer).permit(:text)
  end

end

crossityEnglishApp/app/controllers/asks_controller.rb
class AsksController < ApplicationController

  def create

    @ask = Ask.create(create_params)
    redirect_to :root and return
  end
    def create_params
    params.require(:ask).permit(:text).merge(user_id: current_user.id, question_id: params[:question_id])

    end
end

crossityEnglishApp/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
  end

  def update_params
    params.require(:group).permit(:key, :detail)
  end
end

crossityEnglishApp/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @question = Question.new
    @questions = Question.all.includes(:participants)
    @participant = Participant.new
    @feed_contents = current_user.group.feed_contents.includes(:content).page(params[:page]).per(5)
    @feed_contents_resource = @feed_contents.map(&:content)
    @find = Participant.find_by(question_id:params[:id], user_id: params[current_user.id], number: "1")

  end
end

crossityEnglishApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @questions = @user.answered_questions.uniq
  end
  def edit

  end
  def update
    current_user.update(update_params)
  end
  private
  def update_params
    params.require(:user).permit(:family_name, :first_name, :nickname, :family_name_kana, :first_name_kana, :avatar, :country, :language, :pastime)
  end
end

crossityEnglishApp/app/helpers/answers_helper.rb
module AnswersHelper
end

crossityEnglishApp/app/helpers/application_helper.rb
module ApplicationHelper
end

crossityEnglishApp/app/helpers/asks_helper.rb
module AsksHelper
end

crossityEnglishApp/app/helpers/groups_helper.rb
module GroupsHelper
end

crossityEnglishApp/app/helpers/participant_helper.rb
module ParticipantHelper
end

crossityEnglishApp/app/helpers/participants_helper.rb
module ParticipantsHelper
end

crossityEnglishApp/app/helpers/questions_helper.rb
module QuestionsHelper
end

crossityEnglishApp/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

crossityEnglishApp/app/helpers/top_helper.rb
module TopHelper
end

crossityEnglishApp/app/helpers/users_helper.rb
module UsersHelper
end

crossityEnglishApp/app/views/answers/_answer.html.erb
<div class="answer_content top_content">
  <header class="answer_header">
    <div class="answer_image icon_image" style="background-image: url(<%= answer.user.avatar.url(:medium) %>);"></div>
    <div class="answer_user_info user_info">
      <span><%= link_to answer.user.nickname, user_path(answer.user) %></span>
      <time><%= time_ago_in_words answer.updated_at %></time>
    </div>
  </header>
  <div class="answer_body">
    <div class="answerd">
  [<%=answer.question.when%>] [<%= answer.question.user.nickname %>]さんのMeet-Up<%= link_to "", question_path(answer.question) %>に回答しました。
    </div>
    <% if answer.question.answered?(current_user)%>
    <div class="answer_box">
      <span class="a">Q</span>
      <span class="answer_text"><%= answer.text %></span>
      <% if answer.user_id == current_user.id %>
        <small class="edit">
          <%= link_to '編集', edit_answer_path(answer) %>
        </small>
      <% end %>
    </div>
    <% end %>
    <% if answer.question.answers.count > 1 %>
      <div class="answer_other">
        <%= link_to "他#{answer.question.answers.count - 1}件の回答/ #{answer.question.answers.count - 1} More Answers", question_path(answer.question) %>
      </div>
    <% end %>
  </div>
</div>

crossityEnglishApp/app/views/answers/create.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>送信しました。/ Sent </h3>
    <!-- <span>他の人の回答を見る/ Check Other Questions</span> -->
    <%= link_to "ホームに戻る/ Return Home", root_path  %>
    <p><%= link_to "他の質問を見る/ Check Other Questions", question_path(@answer.question) %></p>
  </div>
</div>

crossityEnglishApp/app/views/answers/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for(@answer) do |f| %>
      <h3><span>Q</span><%= @question.text %></h3>
      <div class="form-group">
        <%= f.text_area :text, placeholder: "回答を入力してください", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
      </div>
      <%= f.submit "回答する", class:"btn btn-primary withripple"%>
    <% end %>
  </div>
</div>

crossityEnglishApp/app/views/answers/new.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for(@answer) do |f| %>
      <h3><span>Q</span><%= @question.text %></h3>
      <div class="form-group">
        <%= f.text_area :text, placeholder: "入力してください/ Please Write Here", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
      </div>
      <%= f.hidden_field :question_id %>
      <%= f.submit "送信/ Send", class:"btn btn-primary withripple"%>
    <% end %>
  </div>
</div>

crossityEnglishApp/app/views/answers/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>回答を編集しました。</h3>
    <%= link_to "他の質問を見る", user_path(current_user) %>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>

crossityEnglishApp/app/views/groups/edit.html.erb
<% provide :title, " ｜ "グループ情報編集 %>
<div class="row form">
  <div class="col-lg-12">
    <%= form_for @group do |f| %>
      <h3>グループ情報を編集する</h3>
      <div class="form-group">
        <%= f.label :key, :Name, class: "control-label" %>
        <%= f.text_field :key, placeholder: "グループ名を入力して下さい", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :detail, :Detail, class: "control-label" %>
        <%= f.text_area :detail, placeholder: "グループ概要を入力してください", size: "30x10", class: "form-control" %>
      </div>
      <%= f.submit "送信", class: "btn btn-primary withripple" %>
    <% end %>
  </div>
</div>

crossityEnglishApp/app/views/groups/show.html.erb
<% provide :title, " ｜ #{@group.key}さん" %>
<div class="row form">
  <div class="col-lg-12">
    <h3><%= @group.key %>
      <small class="edit">
        <%= link_to "編集", edit_group_path(@group) %>
      </small>
    </h3>
    <p><%= @group.detail.blank? ? "このグループの説明はありません" : @group.detail %></p>
    <div class="group_action panel panel-default"></div>
     <h3>Member List</h3>
    <div class="list-group">
    <% @group.users.each do |user| %>
      <div class="list-group-item"><%= link_to user.name, user_path(user) %><hr></div>
    <% end %>
    </div>
  </div>
</div>

crossityEnglishApp/app/views/groups/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>グループの編集が完了しました。</h3>
    <%= link_to "一覧に戻る", group_path(@group) %>
  </div>
</div>