crossityEnglishApp/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  omniauth_callbacks: "omniauth_callbacks"
  }
  root "top#index"
  get "/answers/:id", to: "answers#new"
  patch "/questions/:id", to: "questions#update"
  resources :users, only: [:show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only:[:create, :show, :new]
  resources :answers, only: [:new, :create, :edit, :update]
  resources :participants, only: [:create, :update, :show, :destroy]
  resources :asks, only: [:create, :update, :show]


end

crossityEnglishApp/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_one :feed_content, as: :content, dependent: :destroy

   #callback
  after_create :create_feed_content
  after_update :update_feed_content

  #validation
  validates_presence_of :user_id, :text

  def update_feed_content
    self.feed_content.update(updated_at: updated_at)
  end

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: question.group_id, updated_at: updated_at)
  end

end

crossityEnglishApp/app/models/ask.rb
class Ask < ActiveRecord::Base
  has_many :questions
  belongs_to :user
  validates_presence_of :text

end

crossityEnglishApp/app/models/feed_content.rb
class FeedContent < ActiveRecord::Base
  belongs_to :content, polymorphic: true
end

crossityEnglishApp/app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :questions, ->{ order("created_at DESC") }
  has_many :feed_contents, ->{ order("updated_at DESC") }
end

crossityEnglishApp/app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

crossityEnglishApp/app/models/question.rb
class Question < ActiveRecord::Base
  after_create :create_feed_content

  has_many :participants
  has_many :asks
  belongs_to :group
  belongs_to :user
  has_many :answers
  has_one :feed_content, as: :content, dependent: :destroy
  has_many :pushed_users, through: :participants, source: :user
  validates_presence_of :user_id, :group_id,:when, :where, :what


  def user_answer(user_id)
    def user_answer(user_id)
    Answer.find_by(user_id: user_id, question_id: id)
  end
  end

  def answered?(user)
    answers.exists?(user_id: user.id)
  end

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: group_id, updated_at: updated_at)
  end
end

crossityEnglishApp/app/models/social_profile.rb
class SocialProfile < ActiveRecord::Base
  belongs_to :user

  def set_values(omniauth)
    return if provider.to_s != omniauth['provider'].to_s || uid != omniauth['uid']
    credentials = omniauth['credentials']
    info = omniauth['info']

    self.access_token = credentials['refresh_token']
    self.access_secret = credentials['secret']
    self.credentials = credentials.to_json
    self.name = info['name']
    self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
end

crossityEnglishApp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,authentication_keys: [:email, :group_key]

  attr_accessor :group_key
  has_many :participants
  belongs_to :group
  has_many :questions, ->{order("created_at DESC")}, through: :participants
  has_many :answers, ->{ order("updated_at DESC") }
  has_many :answered_questions, through: :answers, source: :question
  has_many :social_profiles, dependent: :destroy

    #validation
  before_validation :group_key_to_id, if: :has_group_key?

  def social_profile(provider)
    social_profiles.select{ |sp| sp.provider == provider.to_s }.first
  end

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      group_key = conditions.delete(:group_key)
      group_id = Group.where(key: group_key).first
      email = conditions.delete(:email)

      # devise認証を、複数項目に対応させる
      if group_id && email
        where(conditions).where(["group_id = :group_id AND email = :email",
          { group_id: group_id, email: email }]).first
      elsif conditions.has_key?(:confirmation_token)
        where(conditions).first
      else
        false
      end
    end

    def has_group_key?
      group_key.present?
    end

    def group_key_to_id
      group = Group.where(key: group_key).first_or_create
      self.group_id = group.id
    end

    def name
    "#{family_name} #{first_name}"
    end

    def name_kana
    "#{family_name_kana} #{first_name_kana}"
    end

     has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
     validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
     def full_profile?
      avatar? && family_name? && first_name? && family_name_kana? && first_name_kana?
       end

end

crossityEnglishApp/app/controllers/asks_controller.rb
class AsksController < ApplicationController

  def create

    @ask = Ask.create(create_params)
    redirect_to :root and return
  end
    def create_params
    params.require(:ask).permit(:text).merge(user_id: current_user.id, question_id: params[:question_id])

    end
end

crossityEnglishApp/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @question = Question.new
    @questions = Question.all.includes(:participants)
    @participant = Participant.new
    @feed_contents = current_user.group.feed_contents.includes(:content).page(params[:page]).per(5)
    @feed_contents_resource = @feed_contents.map(&:content)
    @find = Participant.find_by(question_id:params[:id], user_id: params[current_user.id], number: "1")

  end
end

crossityEnglishApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @questions = @user.answered_questions.uniq
  end
  def edit

  end
  def update
    current_user.update(update_params)
  end
  private
  def update_params
    params.require(:user).permit(:family_name, :first_name, :nickname, :family_name_kana, :first_name_kana, :avatar, :country, :language, :pastime)
  end
end

crossityEnglishApp/app/helpers/answers_helper.rb
module AnswersHelper
end

crossityEnglishApp/app/helpers/application_helper.rb
module ApplicationHelper
end

crossityEnglishApp/app/helpers/asks_helper.rb
module AsksHelper
end

crossityEnglishApp/app/helpers/groups_helper.rb
module GroupsHelper
end

crossityEnglishApp/app/helpers/participant_helper.rb
module ParticipantHelper
end

crossityEnglishApp/app/helpers/participants_helper.rb
module ParticipantsHelper
end

crossityEnglishApp/app/helpers/questions_helper.rb
module QuestionsHelper
end

crossityEnglishApp/app/helpers/top_helper.rb
module TopHelper
end

crossityEnglishApp/app/helpers/users_helper.rb
module UsersHelper
end

crossityEnglishApp/app/views/common/_header.html.erb
<% if user_signed_in? %>
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <div class="navbar-collapse collapse navbar-responsive-collapse navbar-right">
        <ul class="nav navbar-nav">
          <li><%= link_to "HOME", root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Group <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
            <li><%= link_to current_user.group.key, group_path(current_user.group) %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Log-out", destroy_user_session_path, method: :delete%></li>
              <li><%= link_to "My page", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user)%></li>
            </ul>
          </li>
        </ul>
      </div>
      <%= link_to root_path, :class => 'navbar-brand' do %>
        <%= image_tag 'logo.png' %> <small class='hidden-xs hidden-sm'>外国人と気軽にランチ・ディナーに行こう！</small>
      <% end %>
      <!-- <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'HOME', root_path %></li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アカウント <span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
            </ul>
          </li>
        </ul>
      </div> -->
    </div>
  </div>
<% end %>

crossityEnglishApp/app/views/common/_login_logo.html.erb
<div class='sign_up_logo'>
  <%= image_tag 'logo.png' %>
  <small>外国人と気軽にランチ・ディナーに行こう！</small>
</div>

crossityEnglishApp/app/views/daily_notifier/notify.text.erb
Hi

crossityEnglishApp/app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to root_path, :class => 'navbar-brand' do %>
        <%= image_tag 'logo.png' %> <small class='hidden-xs hidden-sm'>外国人と気軽にランチ・ディナーに行こう！</small>
      <% end %>
      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'HOME', root_path %></li>
           <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">グループ <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to current_user.group.key, group_path(current_user.group) %></li>
      </ul>
    </li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>アカウント <span class='caret'></span></a>
            <ul class='dropdown-menu' role='menu'>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

crossityEnglishApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Profy<%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <script type='text/javascript' charset='utf-8'>
      $(function(){
        $.material.init();
      });
    </script>
    <%= render partial: 'common/header' %>
    <div class='container'>
      <div class='row'>
        <div class='col-lg-12'>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer class='row text-center'>
        <p>(C) Crossity 2018</p>
      </footer>
    </div>
  </body>
</html>