crossityEnglishApp/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  omniauth_callbacks: "omniauth_callbacks"
  }
  root "top#index"
  get "/answers/:id", to: "answers#new"
  patch "/questions/:id", to: "questions#update"
  resources :users, only: [:show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only:[:create, :show, :new]
  resources :answers, only: [:new, :create, :edit, :update]
  resources :participants, only: [:create, :update, :show, :destroy]
  resources :asks, only: [:create, :update, :show]


end

crossityEnglishApp/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_one :feed_content, as: :content, dependent: :destroy

   #callback
  after_create :create_feed_content
  after_update :update_feed_content

  #validation
  validates_presence_of :user_id, :text

  def update_feed_content
    self.feed_content.update(updated_at: updated_at)
  end

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: question.group_id, updated_at: updated_at)
  end

end

crossityEnglishApp/app/models/ask.rb
class Ask < ActiveRecord::Base
  has_many :questions
  belongs_to :user
  validates_presence_of :text

end

crossityEnglishApp/app/models/feed_content.rb
class FeedContent < ActiveRecord::Base
  belongs_to :content, polymorphic: true
end

crossityEnglishApp/app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :questions, ->{ order("created_at DESC") }
  has_many :feed_contents, ->{ order("updated_at DESC") }
end

crossityEnglishApp/app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

crossityEnglishApp/app/models/question.rb
class Question < ActiveRecord::Base
  after_create :create_feed_content

  has_many :participants
  has_many :asks
  belongs_to :group
  belongs_to :user
  has_many :answers
  has_one :feed_content, as: :content, dependent: :destroy
  has_many :pushed_users, through: :participants, source: :user
  validates_presence_of :user_id, :group_id,:when, :where, :what


  def user_answer(user_id)
    def user_answer(user_id)
    Answer.find_by(user_id: user_id, question_id: id)
  end
  end

  def answered?(user)
    answers.exists?(user_id: user.id)
  end

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: group_id, updated_at: updated_at)
  end
end

crossityEnglishApp/app/models/social_profile.rb
class SocialProfile < ActiveRecord::Base
  belongs_to :user

  def set_values(omniauth)
    return if provider.to_s != omniauth['provider'].to_s || uid != omniauth['uid']
    credentials = omniauth['credentials']
    info = omniauth['info']

    self.access_token = credentials['refresh_token']
    self.access_secret = credentials['secret']
    self.credentials = credentials.to_json
    self.name = info['name']
    self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
end

crossityEnglishApp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,authentication_keys: [:email, :group_key]

  attr_accessor :group_key
  has_many :participants
  belongs_to :group
  has_many :questions, ->{order("created_at DESC")}, through: :participants
  has_many :answers, ->{ order("updated_at DESC") }
  has_many :answered_questions, through: :answers, source: :question
  has_many :social_profiles, dependent: :destroy

    #validation
  before_validation :group_key_to_id, if: :has_group_key?

  def social_profile(provider)
    social_profiles.select{ |sp| sp.provider == provider.to_s }.first
  end

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      group_key = conditions.delete(:group_key)
      group_id = Group.where(key: group_key).first
      email = conditions.delete(:email)

      # devise認証を、複数項目に対応させる
      if group_id && email
        where(conditions).where(["group_id = :group_id AND email = :email",
          { group_id: group_id, email: email }]).first
      elsif conditions.has_key?(:confirmation_token)
        where(conditions).first
      else
        false
      end
    end

    def has_group_key?
      group_key.present?
    end

    def group_key_to_id
      group = Group.where(key: group_key).first_or_create
      self.group_id = group.id
    end

    def name
    "#{family_name} #{first_name}"
    end

    def name_kana
    "#{family_name_kana} #{first_name_kana}"
    end

     has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
     validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
     def full_profile?
      avatar? && family_name? && first_name? && family_name_kana? && first_name_kana?
       end

end

crossityEnglishApp/app/controllers/asks_controller.rb
class AsksController < ApplicationController

  def create

    @ask = Ask.create(create_params)
    redirect_to :root and return
  end
    def create_params
    params.require(:ask).permit(:text).merge(user_id: current_user.id, question_id: params[:question_id])

    end
end

crossityEnglishApp/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
  end

  def update_params
    params.require(:group).permit(:key, :detail)
  end
end

crossityEnglishApp/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


  def create
    Question.create(create_params)
    redirect_to :root and return
  end

   def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @users = Participant.where(question_id: @question.id)
    @asks = Ask.where(params[:id])
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @question_id = params[:question_id]
    @ask = Ask.new

  end

  def update
    @question = Question.create(text: params[:text], user_id: params[current_user.id])
    redirect_to :root and return
  end


  def join
    @user = User.find(params[:id])

  end

  private
    def create_params
      params.require(:question).permit(:when,:where,:what,:how_much).merge(user_id: current_user.id, group_id: current_user.group_id)
    end
end

crossityEnglishApp/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @question = Question.new
    @questions = Question.all.includes(:participants)
    @participant = Participant.new
    @feed_contents = current_user.group.feed_contents.includes(:content).page(params[:page]).per(5)
    @feed_contents_resource = @feed_contents.map(&:content)
    @find = Participant.find_by(question_id:params[:id], user_id: params[current_user.id], number: "1")

  end
end

crossityEnglishApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @questions = @user.answered_questions.uniq
  end
  def edit

  end
  def update
    current_user.update(update_params)
  end
  private
  def update_params
    params.require(:user).permit(:family_name, :first_name, :nickname, :family_name_kana, :first_name_kana, :avatar, :country, :language, :pastime)
  end
end

crossityEnglishApp/app/helpers/answers_helper.rb
module AnswersHelper
end

crossityEnglishApp/app/helpers/application_helper.rb
module ApplicationHelper
end

crossityEnglishApp/app/helpers/asks_helper.rb
module AsksHelper
end

crossityEnglishApp/app/helpers/groups_helper.rb
module GroupsHelper
end

crossityEnglishApp/app/helpers/participant_helper.rb
module ParticipantHelper
end

crossityEnglishApp/app/helpers/participants_helper.rb
module ParticipantsHelper
end

crossityEnglishApp/app/helpers/questions_helper.rb
module QuestionsHelper
end

crossityEnglishApp/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

crossityEnglishApp/app/helpers/top_helper.rb
module TopHelper
end

crossityEnglishApp/app/helpers/users_helper.rb
module UsersHelper
end

crossityEnglishApp/app/views/questions/_answer.html.erb
<section class="col-md-12">
  <div class="sct-inner">
    <p><%= link_to answer.user.nickname, user_path(answer.user) %>さん</p>
    <h4><%= @ask %></h4>
    <h4>→<%= answer.text %></h4>
  </div>

</section>

crossityEnglishApp/app/views/questions/_question.html.erb
<div class="question_content top_content">
  <header class="question_header">
    <div class="question_image icon_image" style="background-image: url(<%= question.user.avatar.url(:medium) %>);"></div>
    <div class="question_user_info user_info">
      <span><%= link_to question.user.nickname, user_path(question.user) %></span>
      <time><%= time_ago_in_words question.created_at %></time>
    </div>
  </header>
  <div class="question_body">
    <div class="question_box">
      <span class="q">When :</span>
      <span class="question_text"><%= question.when %></span>
    </div>

    <div class="question_box">
      <span class="q">Where :</span>
      <span class="question_text"><%= question.where %></span>
    </div>

    <div class="question_box">
      <span class="q">What :</span>
      <span class="question_text"><%= question.what %></span>
    </div>

  </div>

    <div class="questioned">
      <%= link_to "質問#{question.asks.count}件 参加#{question.participants.count}人", question_path(question) %>

    </div>


    <%= form_tag(new_question_path, method: :get, class: "question_submit") do %>
      <%= hidden_field_tag(:question_id, question.id) %>
      <%= submit_tag("質問/Ask") %>
    <% end %>

  <% unless question.participants.exists?(user_id: current_user.id)%>
    <div class="join_submit">
      <%= form_for (@participant) do |f| %>
        <%= f.hidden_field_tag(:question_id, question.id) %>
        <%= f.hidden_field_tag(:user_id, current_user.id) %>
        <%= f.hidden_field_tag(:number, "1") %>
        <%= f.hidden_field_tag(:nickname, current_user.nickname) %>
        <%= f.submit ("参加/Join") %>
      <% end %>
    </div>
  <% else %>
      <%= form_tag(participant_path(question.id), method: :delete, class: "join_submit") do %>
        <%= submit_tag ("キャンセル/Cancel") %>
      <% end %>

  <% end %>
</div>

crossityEnglishApp/app/views/questions/new.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for(@ask) do |f| %>
      <h3><span>Q</span><%= @question.text %></h3>
      <div class="form-group">
        <%= f.text_area :text, placeholder: "入力してください/ Please Write Here", cols:"30", rows:"10", autofocus:"true", class:"form-control" %>
      </div>
      <%= f.hidden_field_tag(:question_id, params[:question_id]) %>
      <%= f.submit "送信/ Send", method: :post, class:"btn btn-primary withripple"%>
    <% end %>
  </div>
</div>

crossityEnglishApp/app/views/questions/show.html.erb
<div class="row form">
  <div class="col-lg-12">

    <% if @question.asks.present? %>
      <h3><span>Q</span>Questions</h3>
      <% @asks.each_with_index do |ask, i|  %>
      <h4><%= i+1 %>. <%= ask.text %></h4>
      <% end %>
      <% if @question.answered?(current_user) %>
      <%= render partial: "questions/answer", collection: @answers %>
      <% end %>
    <% end %>

    <div class="group_action panel panel-default">
      <div class="panel-body">
        <% if @question.asks.exists?(user_id: current_user.id) %>
          <%= link_to '回答する/Answer', "/answers/#{@question.id}" %>
        <% else %>
          <h4>※質問がありません※</h4>
        <% end %>
      </div>
    </div>

    <% if @users.present? %>
      <h3><span>I</span>参加者 /Participants</h3>

      <p>
      <% @users.each_with_index do |user, i|  %>
        <%= i+1 %>. <%= user.nickname %>さん
      <% end %>
    <% end %></p>
  </div>
  <div class="col-lg-12">
    <%= link_to "ホームに戻る/ Return Home", root_path %>
</div>

  </div>
  </div>